// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using banheiro_livre;

namespace banheiro_livre.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20191105165631_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("banheiro_livre.Banheiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Banheiro");
                });

            modelBuilder.Entity("banheiro_livre.LimpezaBanheiro", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BanheiroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dia")
                        .HasColumnType("TEXT")
                        .HasMaxLength(3);

                    b.Property<DateTime>("Final")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsavelLimpeza")
                        .HasColumnType("TEXT");

                    b.Property<int>("Serviço")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "BanheiroId", "Dia");

                    b.HasIndex("BanheiroId");

                    b.ToTable("LimpezaBanheiro");
                });

            modelBuilder.Entity("banheiro_livre.LimpezaBanheiro", b =>
                {
                    b.HasOne("banheiro_livre.Banheiro", "Banheiro")
                        .WithMany("LimpezaBanheiros")
                        .HasForeignKey("BanheiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
